name: news_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  dio: ^5.6.0
  logger: ^2.4.0
  shared_preferences: ^2.3.1
  awesome_dio_interceptor: ^1.2.0
  injectable: ^2.4.4
  retrofit: ^4.1.0
  get_it: ^7.7.0
  provider: ^6.1.2
  flutter_svg: ^2.0.10+1
  gap: ^3.0.1
  sprung: ^3.0.1
  otp_text_field:
    git:
      url: https://github.com/Emmanueloluwadamilola/OTPTextField.git
  firebase_core: ^3.4.1
  firebase_auth: ^5.2.1
  cloud_firestore: ^5.4.1
  carousel_slider: ^5.0.0
  json_annotation: ^4.9.0
  flutter_animate: ^4.5.0
  timeago: ^3.7.0
  intl: ^0.19.0
  url_launcher: ^6.3.0
  share_plus: ^10.0.2
  uuid: ^4.5.1
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2
  firebase_storage: ^12.3.4
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.9
  injectable_generator: ^2.6.1
  json_serializable: ^6.8.0
  retrofit_generator: ^8.1.0


  flutter_lints: ^3.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/vectors/
    - assets/fonts/
    - assets/images/

  fonts:
    - family: light
      fonts:
        - asset: assets/fonts/Outfit-Light.ttf
          weight: 300

    - family: regular
      fonts:
        - asset: assets/fonts/Outfit-Regular.ttf 
          weight: 400

    - family: medium
      fonts:
        - asset: assets/fonts/Outfit-Medium.ttf
          weight: 500

    - family: bold
      fonts:
        - asset: assets/fonts/Outfit-Bold.ttf
          weight: 700

    - family: belgrano
      fonts:
        - asset: assets/fonts/Belgrano-Regular.ttf
          weight: 700

